import type { BasePriceRange } from "../../shared/types";

export const impermeabilizzareTettoPricing: BasePriceRange = {
  nationalRange: "25–60 € al mq",
  pricePerSquareMeter: "da 25 € a 60 € al mq",
  sourceLabel: "Prezzari ufficiali delle Regioni Friuli Venezia Giulia e Lombardia, elaborati in fasce di mercato",
  sourceYear: "2025–2026",
  sourceType: "mixed",
  priceRows: [
    {
      id: "impermeabilizzare-tetto-scenario-guaina-standard",
      label: "Guaina bituminosa standard",
      category: "Scenari di impermeabilizzazione",
      unit: "al m²",
      range: "25–40 €/m²",
      note: "",
      confidence: "media",
      costType: "complete",
      role: "primary",
    },
    {
      id: "impermeabilizzare-tetto-scenario-guaina-ardesiata",
      label: "Guaina ardesiata a vista",
      category: "Scenari di impermeabilizzazione",
      unit: "al m²",
      range: "30–50 €/m²",
      note: "",
      confidence: "media",
      costType: "complete",
      role: "scenario",
    },
    {
      id: "impermeabilizzare-tetto-scenario-doppio-strato",
      label: "Sistema a doppio strato",
      category: "Scenari di impermeabilizzazione",
      unit: "al m²",
      range: "35–90 €/m²",
      note: "",
      confidence: "media",
      costType: "complete",
      role: "scenario",
    },
    {
      id: "impermeabilizzare-tetto-guaina-liscia",
      label: "Guaina bituminosa standard (liscia)",
      category: "Nuova impermeabilizzazione",
      unit: "al mq",
      range: "da 25 € a 40 € al mq",
      plainExplanation: "Membrana bituminosa liscia senza protezione minerale: è la soluzione base per una nuova impermeabilizzazione. La fascia comprende materiale e posa.",
      note: "Fascia editoriale basata sul prezzo ufficiale del Prezzario Regione Friuli Venezia Giulia 2025 (27,43 €/m² per la voce di capitolato equivalente), allargata per riflettere la variabilità reale del mercato privato: il valore del prezzario resta il riferimento tecnico puntuale, non è il prezzo esatto mostrato qui.",
      includes: "fornitura della membrana bituminosa e posa in opera",
      excludes: "rimozione della vecchia guaina, ripristini importanti del supporto, ponteggi, difficoltà particolari di accesso",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "impermeabilizzare-tetto-guaina-ardesiata",
      label: "Guaina ardesiata per copertura a vista",
      category: "Nuova impermeabilizzazione",
      unit: "al mq",
      range: "da 30 € a 50 € al mq",
      plainExplanation: "Membrana bituminosa con scaglie minerali superficiali, adatta quando resta esposta perché offre protezione dai raggi UV. La fascia comprende materiale e posa.",
      note: "Fascia editoriale basata sul prezzo ufficiale del Prezzario Regione Friuli Venezia Giulia 2025 (29,10 €/m² per la voce di capitolato equivalente, distinta dalla guaina liscia), allargata per riflettere la variabilità reale del mercato privato.",
      includes: "fornitura della membrana e posa in opera",
      excludes: "rimozione della vecchia guaina, ripristini importanti del supporto, ponteggi, difficoltà particolari di accesso",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "impermeabilizzare-tetto-membrana-standard",
      label: "Impermeabilizzazione bituminosa a doppio strato",
      category: "Nuova impermeabilizzazione",
      unit: "al mq",
      range: "da 35 € a 55 € al mq",
      plainExplanation: "Sistema con due membrane bituminose sovrapposte, per una maggiore tenuta all’acqua su coperture più esposte o con pendenze minime. La fascia comprende materiale e posa.",
      note: "Fascia editoriale basata sul prezzo ufficiale del Prezzario Regione Friuli Venezia Giulia 2025 (35,32 €/m² per la voce di capitolato equivalente, indicata nel prezzario come \"membrana bituminosa standard\"), allargata per riflettere la variabilità reale del mercato privato.",
      includes: "fornitura delle due membrane e posa in opera",
      excludes: "rimozione della vecchia guaina, ripristini importanti del supporto, ponteggi, difficoltà particolari di accesso",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "impermeabilizzare-tetto-doppia-membrana-alluminio",
      label: "Doppia guaina con protezione in alluminio",
      category: "Nuova impermeabilizzazione",
      unit: "al mq",
      range: "da 45 € a 60 € al mq",
      plainExplanation: "Sistema a doppio strato con finitura riflettente in alluminio, autoprotetta e adatta a coperture esposte. La fascia comprende materiale e posa.",
      note: "Fascia editoriale basata sul prezzo ufficiale del Prezzario Regione Friuli Venezia Giulia 2025 (44,40 €/m² per la voce di capitolato equivalente), allargata per riflettere la variabilità reale del mercato privato.",
      includes: "fornitura del sistema a doppio strato e posa in opera",
      excludes: "rimozione della vecchia guaina, ripristini importanti del supporto, ponteggi, difficoltà particolari di accesso",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "impermeabilizzare-tetto-doppia-membrana-rame",
      label: "Doppia guaina con protezione in rame",
      category: "Nuova impermeabilizzazione",
      unit: "al mq",
      range: "da 75 € a 90 € al mq",
      plainExplanation: "Sistema a doppio strato autoprotetto con lamina di rame: rispetto all’alluminio ha un costo maggiore e una resa estetica e durabilità differenti. La fascia comprende materiale e posa.",
      note: "Fascia editoriale che unifica i prezzi ufficiali del Prezzario Regione Friuli Venezia Giulia 2025 per le due varianti di grammatura del rame (4 kg/m²: 79,24 €/m²; 4,5 kg/m²: 81,36 €/m²): per un cliente privato sono due varianti troppo simili per giustificare due voci separate. La grammatura esatta resta un dettaglio da confermare con il professionista, non cambia la fascia mostrata qui.",
      includes: "fornitura del sistema a doppio strato con lamina di rame e posa in opera",
      excludes: "rimozione della vecchia guaina, ripristini importanti del supporto, ponteggi, difficoltà particolari di accesso",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "impermeabilizzare-tetto-lisciatura-piano-posa",
      label: "Preparazione e livellamento della superficie",
      category: "Preparazione della superficie",
      unit: "al mq",
      range: "da 10 € a 20 € al mq",
      plainExplanation: "Lavorazione condizionale sintetizzata anche negli Extra: può servire quando il fondo esistente è irregolare o deteriorato e deve essere regolarizzato prima della posa della nuova guaina. Non va sommata due volte se già compresa nel preventivo.",
      note: "Tecnicamente è la preparazione del \"piano di posa\". Fascia editoriale basata sul prezzo ufficiale del Prezzario Regione Lombardia 1/2026 (13,22 €/m² per la voce di capitolato equivalente), allargata per riflettere la variabilità reale del mercato privato.",
      includes: "regolarizzazione della superficie prima della posa della nuova guaina",
      excludes: "rimozione della vecchia guaina (vedi voce dedicata), ponteggi",
      confidence: "media",
      costType: "work",
      role: "extra",
    },
    {
      id: "impermeabilizzare-tetto-rimozione-smaltimento-guaina",
      label: "Rimozione e smaltimento della vecchia guaina",
      category: "Rimozione e riparazioni mirate",
      categoryNote: "Queste lavorazioni non sono comprese nel prezzo delle nuove impermeabilizzazioni qui sopra: si aggiungono solo quando il tuo caso lo richiede.",
      unit: "al mq",
      range: "da 10 € a 20 € al mq",
      plainExplanation: "Lavorazione condizionale sintetizzata anche negli Extra: serve quando la vecchia impermeabilizzazione deve essere rimossa e conferita prima della posa del nuovo sistema. Non va sommata due volte se già compresa nel preventivo.",
      note: "Perimetro ordinario: rimozione, movimentazione, trasporto, smaltimento/conferimento. Il prezzario ufficiale di riferimento (Prezzario Regione Lombardia 1/2026) quota SOLO il conferimento a peso del materiale già rimosso (19,53 € ogni 100 kg) — non l'intera rimozione: la manodopera di rimozione della guaina non è direttamente quotata da nessun prezzario ufficiale consultato per questa guida, la fascia al mq qui mostrata è una stima editoriale. Come ordine di grandezza è coerente con la lavorazione analoga sul manto di copertura (rimozione e smaltimento del vecchio manto, 15–30 €/mq, guida \"Quanto costa rifare un tetto\"), proporzionalmente più leggera perché qui si rimuove una membrana sottile, non l'intera copertura in tegole o coppi. Il valore ufficiale a peso resta un riferimento tecnico utile per chi ha già una stima del peso del materiale, non equivalente a questa fascia al mq.",
      includes: "rimozione della vecchia guaina, movimentazione ordinaria, trasporto, smaltimento/conferimento",
      // "rifiuti" e non "materiali che richiedono...": la parola "materiali"
      // fa scattare per costruzione il badge "Materiali esclusi" su
      // costType "work" (describeCostTypeBadge, cost-guide-price-model.ts)
      // — corretto quando significa "fornitura esclusa", fuorviante qui
      // (amianto/eternit sono uno scarto speciale da bonificare, non un
      // materiale da fornire). Stesso perimetro, parola diversa.
      excludes: "amianto, eternit o altri rifiuti che richiedono una bonifica specifica (non quotabile qui), ponteggi",
      confidence: "media",
      costType: "work",
      role: "extra",
    },
    {
      id: "impermeabilizzare-tetto-ricerca-infiltrazione",
      label: "Ricerca e riparazione di una perdita localizzata",
      category: "Rimozione e riparazioni mirate",
      unit: "a intervento",
      range: "da valutare con il professionista",
      plainExplanation: "Intervento mirato per individuare e riparare una perdita circoscritta, come un manto fessurato in un punto o un’infiltrazione localizzata. È un’alternativa al rifacimento completo quando il problema è limitato, non un Extra da aggiungere normalmente alla nuova impermeabilizzazione.",
      note: "Il prezzo richiede sempre una valutazione: incidono il tempo necessario per individuare la perdita, l'accessibilità, la quantità di superficie danneggiata, i raccordi/comignoli/bocchettoni coinvolti e l'eventuale necessità di estendere la riparazione oltre il punto individuato. I prezzari ufficiali di riferimento (Prezzario Regione Lombardia 1/2026) quotano voci puntuali per casi specifici — riparazione di un manto fessurato 56,56 €/m², ricerca e riparazione di un'infiltrazione isolata 82,63 € cadauna — utili come riferimento tecnico, ma non promettibili come prezzo di mercato per un intervento privato senza sopralluogo.",
      includes: "ricerca del punto di perdita ed eliminazione, secondo l'estensione del danno",
      excludes: "posa di una nuova impermeabilizzazione su tutta la superficie (vedi le voci dedicate qui sopra), ponteggi",
      priceStatus: "quoteRequired",
    },
  ],
  sizeExamples: [],
};
