import type { BasePriceRange } from "../../shared/types";

export const impermeabilizzareTerrazzoPricing: BasePriceRange = {
  nationalRange: "30–70 € al mq",
  pricePerSquareMeter: "da 30 € a 70 € al mq",
  sourceLabel: "Prezzari regionali ufficiali e confronto di mercato nazionale",
  sourceYear: "2025–2026",
  sourceType: "mixed",
  priceRows: [
    {
      id: "impermeabilizzare-terrazzo-cementizia-sotto-pavimento",
      label: "Impermeabilizzazione cementizia sotto pavimento",
      category: "Sistemi di impermeabilizzazione",
      categoryNote: "Questi sistemi sono modi alternativi di impermeabilizzare il terrazzo: scegli quello più adatto al tuo caso, non sommare le fasce tra loro. Non tutti sono calpestabili come una vera pavimentazione: alcuni vanno protetti da un pavimento o da un massetto sopra di loro, altri tollerano solo un'ispezione o un traffico leggero, altri ancora sono pensati per il normale utilizzo pedonale del terrazzo — la differenza è spiegata in ogni voce.",
      unit: "al mq",
      range: "da 20 € a 35 € al mq",
      plainExplanation: "È un sistema impermeabilizzante cementizio applicato sotto la finitura finale: va steso sul massetto oppure, quando tecnicamente possibile, in sovrapposizione a un pavimento esistente stabile, prima della posa del nuovo rivestimento. Non è pensato per restare a vista né per essere calpestato direttamente.",
      note: "Fascia editoriale Esigenta elaborata confrontando i prezzari regionali ufficiali 2025–2026 (Emilia-Romagna, Friuli Venezia Giulia, Sicilia) con il mercato nazionale (Instapro, Edilnet, Homedeal e altre fonti tecniche): nessun prezzario pubblico consultato quota un pacchetto specifico per questo sistema, la fascia riflette l'osservazione generale delle fonti su lavorazioni di impermeabilizzazione più semplici (circa 20–40 €/mq), non il prezzo puntuale di una singola fonte.",
      includes: "fornitura del prodotto cementizio e posa a sistema, compreso il trattamento di raccordi e angoli",
      excludes: "nuova pavimentazione o rivestimento finale, demolizione del pavimento esistente quando necessaria, ripristino del massetto o correzione delle pendenze quando necessari",
      confidence: "media",
      costType: "complete",
      role: "primary",
    },
    {
      id: "impermeabilizzare-terrazzo-trasparente-sopra-piastrelle",
      label: "Impermeabilizzante trasparente sopra piastrelle",
      category: "Sistemi di impermeabilizzazione",
      unit: "al mq",
      range: "da 45 € a 75 € al mq",
      plainExplanation: "È una soluzione per terrazzi pavimentati quando le piastrelle esistenti sono stabili e ben ancorate: mantiene visibile il pavimento sottostante e, quando si usa un prodotto progettato per questo impiego, può costituire una superficie pedonabile. Non è applicabile su qualunque pavimento: distacchi, fessure importanti, problemi del massetto o pendenze errate possono richiedere un intervento diverso.",
      note: "Fascia editoriale Esigenta elaborata dalle stesse fonti generali di questa guida (prezzari regionali 2025–2026 e mercato nazionale): nessuna fonte quota un prezzo puntuale per questo specifico sistema applicato sopra una pavimentazione esistente, la fascia è un'elaborazione per committenza privata.",
      includes: "fornitura del prodotto impermeabilizzante trasparente e posa a sistema sopra la pavimentazione esistente",
      excludes: "rimozione o sostituzione delle piastrelle, ripristino del massetto o correzione delle pendenze quando necessari",
      confidence: "media",
      costType: "complete",
      role: "scenario",
    },
    // Micro-fix 2026-08 (verifica esplicita): plainExplanation di questa
    // riga e di "terrazzo-sistema-complesso" più sotto rese esplicitamente
    // distinte — potendosi sovrapporre economicamente (50–90 vs 70–120
    // €/mq), il rischio era che la seconda leggesse come "la stessa resina
    // ma più cara". Ora ciascuna cita esplicitamente l'altra e la
    // differenza chimica/prestazionale concreta, non solo il prezzo.
    {
      id: "impermeabilizzare-terrazzo-resina-calpestabile-vista",
      label: "Resina impermeabilizzante calpestabile a vista",
      category: "Sistemi di impermeabilizzazione",
      unit: "al mq",
      range: "da 50 € a 90 € al mq",
      plainExplanation: "È un ciclo resinoso — poliuretanico, PMMA o sistemi equivalenti — progettato espressamente come impermeabilizzazione continua e insieme come finitura finale del terrazzo: pensato per il normale traffico pedonale di un'abitazione, con la possibilità di una finitura antiscivolo quando il sistema la prevede. È una voce distinta sia da una semplice guaina liquida (perimetro più semplice, qui sotto) sia dai sistemi specialistici ad alte prestazioni in poliurea (in tabella più sotto), pensati per esigenze diverse dal normale uso residenziale.",
      note: "Fascia editoriale Esigenta elaborata dalle stesse fonti generali di questa guida: nessun prezzario pubblico consultato distingue un sistema resinoso calpestabile a vista come voce a sé, la fascia riflette l'osservazione generale delle fonti sui sistemi più evoluti/specialistici (oltre 70–90 €/mq nella fascia alta), qui estesa verso il basso per coprire anche cicli resinosi più semplici ma comunque calpestabili.",
      includes: "fornitura del ciclo resinoso e posa, compresa la finitura superficiale (anche antiscivolo, quando prevista dal sistema scelto)",
      excludes: "ripristino del massetto o correzione delle pendenze quando necessari, demolizione della pavimentazione esistente",
      confidence: "media",
      costType: "complete",
      role: "scenario",
    },
    {
      id: "impermeabilizzare-terrazzo-guaina-liquida-traffico-leggero",
      label: "Guaina liquida a vista per traffico leggero",
      category: "Sistemi di impermeabilizzazione",
      unit: "al mq",
      range: "da 35 € a 55 € al mq",
      plainExplanation: "Distingue i rivestimenti impermeabilizzanti esposti che tollerano ispezione, manutenzione o un traffico pedonale leggero dai veri sistemi calpestabili per uso normale (riga sopra): non è una pavimentazione pensata per l'uso quotidiano del terrazzo.",
      note: "Fascia editoriale Esigenta elaborata dalle stesse fonti generali di questa guida, posizionata tra i sistemi da ricoprire e i sistemi calpestabili: nessuna fonte quota separatamente una guaina liquida a traffico leggero rispetto a un ciclo calpestabile a uso normale.",
      includes: "fornitura del rivestimento impermeabilizzante liquido e posa in opera",
      excludes: "ripristino del massetto o correzione delle pendenze quando necessari, demolizione della pavimentazione esistente",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "impermeabilizzare-terrazzo-guaina-ardesiata-vista",
      label: "Guaina bituminosa ardesiata a vista",
      category: "Sistemi di impermeabilizzazione",
      unit: "al mq",
      range: "da 25 € a 45 € al mq",
      plainExplanation: "È una guaina bituminosa con una finitura minerale (ardesiata) che resta a vista: indicata soprattutto per lastrici solari, terrazzi non utilizzati come vero spazio abitabile o superfici destinate principalmente a manutenzione e ispezione — non equivalente a una pavimentazione calpestabile.",
      note: "Fascia editoriale Esigenta elaborata dalle stesse fonti generali di questa guida: nessuna delle fonti consultate per l'impermeabilizzazione del terrazzo quota un prezzo puntuale per questo sistema in questo contesto applicativo (a differenza della guida gemella sul tetto, che ha un'ancora ufficiale specifica riferita alla copertura inclinata, non riportata qui perché il contesto applicativo è diverso).",
      includes: "fornitura della membrana bituminosa ardesiata e posa in opera",
      excludes: "rimozione della vecchia impermeabilizzazione quando presente, massetto di protezione o pavimentazione sovrastante, ripristino del massetto o correzione delle pendenze quando necessari",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "impermeabilizzare-terrazzo-doppia-guaina-bituminosa",
      label: "Impermeabilizzazione con doppia guaina bituminosa",
      category: "Sistemi di impermeabilizzazione",
      unit: "al mq",
      range: "da 35 € a 55 € al mq",
      plainExplanation: "È lo stesso principio della guaina bituminosa ardesiata qui sopra, realizzato con due membrane sovrapposte invece di una, per una tenuta all'acqua maggiore utile su superfici più esposte o con pendenze minime. Anche questo sistema resta a vista e non è una pavimentazione calpestabile per l'uso quotidiano: valgono le stesse indicazioni della guaina ardesiata qui sopra. Un eventuale massetto di protezione, una pavimentazione o altri quadrotti sopra la guaina restano lavorazioni separate, non comprese qui salvo diverso capitolato.",
      note: "Fascia editoriale Esigenta elaborata dalle stesse fonti generali di questa guida: il sistema a doppia membrana comporta un maggiore impiego di materiale e tempo di posa rispetto alla guaina ardesiata a singolo strato (riga precedente), da cui la fascia leggermente più alta.",
      includes: "fornitura delle due membrane bituminose e posa in opera",
      excludes: "massetto di protezione, pavimentazione, quadrotti o altra finitura pedonabile sovrastante salvo diverso capitolato, ripristino del massetto o correzione delle pendenze quando necessari",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "impermeabilizzare-terrazzo-membrana-sintetica-tpo-pvc",
      label: "Membrana sintetica TPO/PVC",
      category: "Sistemi di impermeabilizzazione",
      unit: "al mq",
      range: "da 60 € a 100 € al mq",
      plainExplanation: "È una membrana sintetica (TPO o PVC) termosaldata, la soluzione più tipica su grandi superfici piane, lastrici e terrazze o coperture di questo tipo: rappresenta lo strato impermeabilizzante, non una pavimentazione finale pensata per il normale utilizzo pedonale del terrazzo. Su terrazzi abitabili va di norma protetta da una pavimentazione o da un'altra finitura pedonabile sopra di lei; su lastrici o coperture non abitate può restare esposta.",
      note: "Fascia editoriale Esigenta elaborata dalle stesse fonti generali di questa guida: nessuna fonte consultata quota specificamente una membrana sintetica TPO/PVC su terrazzo residenziale, la fascia riflette l'osservazione generale delle fonti sui sistemi più evoluti (oltre 70–90 €/mq nella fascia alta) estesa verso il basso per coprire configurazioni di posa più semplici.",
      includes: "fornitura della membrana sintetica e posa con saldatura dei giunti",
      excludes: "pavimentazione o finitura pedonabile sovrastante quando prevista dal caso d'uso, ripristino del massetto o correzione delle pendenze quando necessari",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "terrazzo-sistema-complesso",
      label: "Sistema impermeabilizzante ad alte prestazioni",
      category: "Sistemi di impermeabilizzazione",
      unit: "al mq",
      range: "da 70 € a 120 € al mq",
      plainExplanation: "Comprende sistemi in poliurea o resine specialistiche, chimicamente diversi dal ciclo poliuretanico/PMMA della resina calpestabile standard qui sopra: pensati per interventi che richiedono prestazioni superiori, come maggiore resistenza all'usura o agli agenti chimici, tempi di applicazione e indurimento più rapidi, o cicli tecnici più complessi. Non è semplicemente la stessa resina calpestabile a un prezzo più alto: il sistema specifico, la preparazione del fondo e la modalità applicativa incidono molto sul preventivo, e non è una fascia universale valida per qualunque configurazione.",
      note: "Fascia editoriale Esigenta: la guida originale (2026-08) osservava, confrontando i prezzari regionali ufficiali con il mercato nazionale, che i sistemi specialistici possono superare 70–90 €/mq senza un tetto definito; questa revisione rende quell'osservazione concreta con una fascia superiore definita (70–120 €/mq) invece di lasciarla aperta, restando comunque un'elaborazione editoriale multi-fonte, non il prezzo puntuale di un singolo prezzario.",
      includes: "fornitura del sistema scelto (poliurea o resina specialistica) e posa a ciclo completo, secondo la preparazione del fondo richiesta",
      excludes: "ripristino del massetto o correzione delle pendenze quando necessari, pavimentazione finale quando non prevista dal sistema",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "terrazzo-riparazione-localizzata",
      label: "Riparazione localizzata di un'infiltrazione",
      category: "Riparazioni mirate",
      unit: "a intervento",
      unitLabel: "per intervento",
      range: "da valutare con il professionista",
      plainExplanation: "È l'intervento mirato per trovare e riparare una perdita isolata — uno scarico, un bocchettone, una soglia, un giunto, un raccordo o una piccola zona deteriorata — senza rifare l'impermeabilizzazione dell'intera superficie.",
      note: "Può riguardare uno scarico, un bocchettone, una soglia, un giunto, un raccordo o una piccola zona deteriorata. Per lavori di questo tipo il prezzo al mq è poco significativo: esistono costi minimi di intervento, diagnosi e manodopera che non scendono sotto una certa soglia anche per un danno piccolo.",
      includes: "ricerca del punto di perdita ed eliminazione, secondo l'estensione del danno",
      excludes: "impermeabilizzazione dell'intera superficie (vedi i sistemi qui sopra), demolizione o ripristino del pavimento quando l'estensione del danno lo richiede",
      priceStatus: "quoteRequired",
    },
    {
      id: "impermeabilizzare-terrazzo-demolizione-pavimento-esistente",
      label: "Demolizione e smaltimento del pavimento esistente",
      category: "Lavorazioni accessorie",
      categoryNote: "Queste lavorazioni non sono comprese nei sistemi di impermeabilizzazione qui sopra: si aggiungono solo quando le condizioni del tuo terrazzo lo richiedono, non in ogni intervento.",
      unit: "al mq",
      range: "da 10 € a 25 € al mq",
      plainExplanation: "Rimozione della pavimentazione esistente quando il sistema scelto richiede l’accesso al supporto sottostante, con movimentazione e smaltimento ordinari. Non va conteggiata una seconda volta se già compresa nel preventivo.",
      note: "Fascia editoriale Esigenta elaborata dalle stesse fonti generali di questa guida (prezzari regionali 2025–2026 e mercato nazionale): comprende rimozione, movimentazione, trasporto e smaltimento del pavimento esistente, non un prezzo ufficiale puntuale.",
      includes: "rimozione della pavimentazione esistente, movimentazione, trasporto e smaltimento del materiale di risulta",
      // "nuova pavimentazione o impermeabilizzazione" e non "materiali
      // esclusi": la parola "materiali" fa scattare per costruzione il
      // badge "Materiali esclusi" su costType "work" (describeCostTypeBadge,
      // templates/cost-guide-price-model.ts) — corretto quando significa
      // "fornitura esclusa", fuorviante qui (una demolizione non ha
      // comunque materiali da fornire). Stesso bug reale già corretto su
      // impermeabilizzare-tetto-rimozione-smaltimento-guaina.
      excludes: "ripristino del massetto o correzione delle pendenze quando necessari (vedi voce dedicata), nuova pavimentazione o impermeabilizzazione",
      confidence: "media",
      costType: "work",
      role: "extra",
    },
    {
      id: "impermeabilizzare-terrazzo-ripristino-massetto-pendenze",
      label: "Ripristino del massetto o delle pendenze",
      category: "Lavorazioni accessorie",
      unit: "al mq",
      range: "da 20 € a 50 € al mq",
      plainExplanation: "Intervento sul supporto quando il massetto è deteriorato o serve correggere il deflusso dell’acqua verso scarichi e bocchettoni. Non va conteggiato una seconda volta se già compreso nel preventivo.",
      note: "Fascia editoriale Esigenta elaborata dalle stesse fonti generali di questa guida: il costo cambia molto in base all'estensione dell'intervento (una rasatura localizzata rispetto a una ricostruzione estesa del massetto) e alla correzione delle pendenze necessaria verso gli scarichi.",
      includes: "ricostruzione o rasatura del massetto e/o correzione delle pendenze verso gli scarichi",
      excludes: "demolizione del pavimento esistente quando necessaria (vedi voce dedicata), impermeabilizzazione e nuova pavimentazione",
      confidence: "media",
      costType: "complete",
      role: "extra",
    },
  ],
  sizeExamples: [
    {
      label: "Terrazzo da 20 mq",
      sizeRange: "20 mq",
      range: "da 600 € a 1.400 €",
      note: "Calcolo per un'impermeabilizzazione standard: 20 mq × 30–70 €/mq. Non rappresenta una resina calpestabile, un sistema in poliurea o un rifacimento completo del terrazzo. Nei terrazzi piccoli il costo al mq può risultare più alto: preparazione, accesso, raccordi, scarichi e i costi minimi di cantiere non diminuiscono proporzionalmente alla superficie.",
    },
    {
      label: "Terrazzo da 50 mq",
      sizeRange: "50 mq",
      range: "da 1.500 € a 3.500 €",
      note: "Calcolo per un'impermeabilizzazione standard: 50 mq × 30–70 €/mq. Non rappresenta una resina calpestabile, un sistema in poliurea o un rifacimento completo del terrazzo.",
    },
    {
      label: "Terrazzo da 100 mq",
      sizeRange: "100 mq",
      range: "da 3.000 € a 7.000 €",
      note: "Calcolo per un'impermeabilizzazione standard: 100 mq × 30–70 €/mq. Non rappresenta una resina calpestabile, un sistema in poliurea o un rifacimento completo del terrazzo.",
    },
  ],
};
