import type { BasePriceRange } from "../../shared/types";

export const rifareImpiantoElettricoPricing: BasePriceRange = {
  nationalRange: "55–90 € al mq",
  pricePerSquareMeter: "da 55 € a 90 € al mq",
  sourceLabel: "Prezzari regionali ufficiali e confronto di mercato nazionale",
  sourceYear: "2025–2026",
  sourceType: "mixed",
  priceRows: [
    {
      id: "elettrico-scenario-canalizzazioni-riutilizzabili",
      label: "Rifacimento con canalizzazioni esistenti riutilizzabili",
      category: "Scenari di ampiezza del lavoro",
      categoryNote:
        "Questi tre scenari rappresentano modi diversi di rifare un impianto elettrico, in base a quanto delle canalizzazioni esistenti resta riutilizzabile e a quanto l'impianto risultante è articolato: scegli quello più vicino al tuo caso, non sommare le fasce tra loro.",
      unit: "al mq",
      range: "da 40 € a 60 € al mq",
      plainExplanation:
        "È comunque un rifacimento dell'impianto, non una semplice sostituzione dei frutti: buona parte di corrugati, scatole e percorsi esistenti viene però riutilizzata perché ancora idonea, con meno tracce nuove e meno assistenza muraria rispetto al rifacimento completo.",
      note: "Fascia editoriale Esigenta: si applica quando un sopralluogo conferma che le canalizzazioni esistenti sono davvero riutilizzabili, non per definizione su ogni impianto vecchio.",
      includes:
        "nuovi conduttori dove previsti, punti e apparecchi standard, distribuzione interna, protezioni e quadro adeguati alla configurazione, verifiche finali, Dichiarazione di conformità rilasciata dall'impresa abilitata al termine del lavoro",
      excludes: "nuove tracce diffuse, montante quando da rifare, rifacimento generale della messa a terra, domotica avanzata",
      confidence: "media",
      costType: "complete",
      role: "scenario",
    },
    {
      id: "elettrico-rifacimento-completo",
      label: "Rifacimento completo standard dell'impianto elettrico",
      category: "Scenari di ampiezza del lavoro",
      unit: "al mq",
      range: "da 55 € a 90 € al mq",
      plainExplanation:
        "È lo scenario principale di questa guida: nuovo impianto interno, distribuzione e circuiti ordinari, punti luce/prese/comandi standard, quadro generale completo e protezioni, con le normali tracce necessarie e la loro chiusura grezza.",
      note: "Normali tracce e chiusura grezza comprese; finitura estetica della parete esclusa — non è una formula generica di \"opere murarie comprese\". È la fascia principale di questa guida: un rifacimento con canalizzazioni in buona parte riutilizzabili costa indicativamente meno (vedi lo scenario qui sopra), un impianto più articolato con molte linee dedicate costa indicativamente di più (vedi lo scenario qui sotto).",
      includes:
        "nuovo impianto interno, distribuzione e circuiti ordinari, punti luce/prese/comandi standard, quadro generale completo adeguato alla configurazione, protezioni, normali nuove tracce dove necessarie, chiusura grezza ordinaria delle tracce, verifiche finali, Dichiarazione di conformità rilasciata dall'impresa abilitata al termine del lavoro",
      excludes:
        "rasatura finale diffusa, tinteggiatura, ripristino estetico completo delle pareti, domotica avanzata, aumento della potenza contrattuale, montante contatore-quadro quando da rifare, rifacimento generale dell'impianto di terra quando necessario, lavorazioni eccezionali, prestazioni professionali esterne quando richieste dal caso",
      confidence: "media",
      costType: "complete",
      role: "primary",
    },
    {
      id: "elettrico-scenario-impianto-articolato",
      label: "Impianto più articolato / nuove linee diffuse",
      category: "Scenari di ampiezza del lavoro",
      unit: "al mq",
      range: "da 80 € a 110 € al mq",
      plainExplanation:
        "Per impianti con molte linee dedicate, maggiore suddivisione dei circuiti, un quadro più articolato, nuove tracce diffuse o più punti/distribuzione complessa — non un impianto \"premium\", ma un impianto con più lavoro tecnico da eseguire.",
      note: "Domotica avanzata esclusa anche in questo scenario: quando prevista, resta una valutazione a parte.",
      includes: "molte linee dedicate, maggiore suddivisione dei circuiti, quadro più articolato, nuove tracce diffuse, più punti o distribuzione più complessa",
      excludes: "domotica avanzata",
      confidence: "media",
      costType: "complete",
      role: "scenario",
    },
    {
      id: "elettrico-punto-luce-completo",
      label: "Punto luce completo con un comando",
      category: "Punti elettrici",
      unit: "cadauno",
      unitLabel: "per punto",
      range: "da 70 € a 110 € cad",
      plainExplanation:
        "Comprende uscita luce, comando standard, scatole, corrugato, conduttori, frutti e collegamenti, con la normale traccia locale e chiusura grezza.",
      note: "Fascia editoriale Esigenta, non un prezzo ufficiale puntuale: non è la stessa voce dei prezzi ufficiali di capitolato, che escludono sempre la traccia — un punto luce sotto traccia costa 26,85 € se singolo o 28,96 € se doppio (due punti dalla stessa derivazione), e un punto luce con tubazione a vista, senza incassarlo nel muro, costa 31,88 € (tutti Prezzario Emilia-Romagna 2025); un altro prezzario regionale (Friuli Venezia Giulia 2025) quota una posa a vista con grado di protezione IP54 a 40,55 €, capitolato non equivalente. Nessuna di queste voci ufficiali comprende la traccia: qui invece è compresa.",
      includes: "uscita luce, comando/interruttore standard, tubo corrugato, conduttori, scatole, frutto/supporto/placca standard, collegamenti, normale traccia locale necessaria, fissaggio, chiusura grezza ordinaria",
      excludes: "lampadario, plafoniera o altro corpo illuminante, linea dedicata lunga dal quadro, rasatura finale, tinteggiatura, murature particolari",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-presa-completa-standard",
      label: "Presa elettrica completa standard",
      category: "Punti elettrici",
      unit: "cadauno",
      unitLabel: "per punto",
      range: "da 60 € a 90 € cad",
      plainExplanation:
        "Comprende presa, scatola, supporto e placca standard, corrugato, conduttori e collegamenti, con la normale traccia locale e chiusura grezza.",
      note: "Fascia editoriale Esigenta: non è la stessa voce dei prezzi ufficiali di capitolato, che escludono sempre la traccia — una presa completa 2P+T costa 49,72 € nella versione da 10 A o 56,07 € nella versione da 16 A (Prezzario Emilia-Romagna 2025); un altro prezzario regionale (Friuli Venezia Giulia 2025) quota una presa 2P+T 10A a 79,12 €, con un capitolato di posa diverso, non direttamente equivalente. Nessuna di queste voci ufficiali comprende la traccia: qui invece è compresa.",
      includes: "presa standard, scatola, supporto/placca, tubo/corrugato, conduttori, collegamenti, derivazione ordinaria, normale traccia, fissaggio, chiusura grezza",
      excludes: "linea dedicata lunga, rasatura, tinteggiatura, murature particolari",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-comando-aggiuntivo",
      label: "Comando aggiuntivo (deviato/invertito)",
      category: "Punti elettrici",
      unit: "cadauno",
      unitLabel: "per comando",
      range: "da 45 € a 70 € cad",
      plainExplanation:
        "Permette di comandare una luce già cablata da un secondo punto. Comprende comando, cablaggio, apparecchio e normale lavorazione locale necessaria.",
      note: "Fascia editoriale Esigenta: la vecchia voce ufficiale \"Punto comando deviato\" costava 53,63 € (Prezzario Emilia-Romagna 2025, capitolato analitico con collaudo compreso) ma escludeva la traccia — qui invece è compresa. Se serve invece un punto luce nuovo, vedi \"Punto luce completo con un comando\" qui sopra.",
      includes: "comando aggiuntivo (deviato/invertito) su un punto luce già cablato, traccia locale per il nuovo comando, cablaggio, apparecchio e placca, fissaggio, chiusura grezza",
      excludes: "creazione di un nuovo punto luce indipendente, rasatura finale, tinteggiatura",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-punto-su-predisposizione",
      label: "Punto su predisposizione esistente",
      category: "Punti elettrici",
      unit: "cadauno",
      unitLabel: "per punto",
      range: "da 25 € a 45 € cad",
      plainExplanation:
        "Si applica quando scatola, corrugato e percorso sono già presenti e utilizzabili. Comprende apparecchio, collegamento, posa e verifica.",
      note: "Fascia editoriale Esigenta: un prezzario regionale (Friuli Venezia Giulia 2025) quota una voce simile di sola posa in scatola già predisposta a 15,18 €, senza materiali, tubazione, scatola o cavi. Non è il prezzo di un nuovo punto da creare da zero: se la predisposizione non è già presente e idonea, vedi \"Punto luce completo\" o \"Presa elettrica completa standard\" qui sopra.",
      includes: "apparecchio, collegamento, posa, verifica — solo quando scatola, corrugato/percorso e predisposizione sono già presenti e utilizzabili",
      excludes: "creazione della predisposizione stessa (traccia, scatola, corrugato), verifica dell'idoneità della predisposizione esistente quando richiede lavoro aggiuntivo",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-circuito-standard",
      label: "Circuito interno standard",
      category: "Circuiti e distribuzione",
      categoryNote:
        "I circuiti collegano il quadro alle diverse zone o utenze dell’abitazione. Numero e sezione vengono dimensionati dal professionista in base ai carichi previsti.",
      unit: "cadauno",
      unitLabel: "per circuito",
      range: "da 200 € a 300 € cad",
      plainExplanation:
        "Linea per l’alimentazione ordinaria di illuminazione e prese di una zona dell’abitazione, comprensiva di percorso, conduttori, derivazioni e collegamenti.",
      note: "Fascia editoriale Esigenta: i prezzari ufficiali quotano le sezioni tecniche corrispondenti come \"dorsale interna\" — 2×1,5 mmq + T a 200,14 € e 2×2,5 mmq + T a 205,09 € (Prezzario Emilia-Romagna 2025, unità abitativa tipo, misurata dal centralino di appartamento). Non è il montante contatore-quadro.",
      includes: "linea dal quadro, tubazione/percorso ordinario, conduttori, scatole/derivazioni, collegamenti",
      excludes: "grandi opere murarie, montante contatore-quadro",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-circuito-dedicato",
      label: "Circuito dedicato / sezione maggiore",
      category: "Circuiti e distribuzione",
      unit: "cadauno",
      unitLabel: "per circuito",
      range: "da 250 € a 400 € cad",
      plainExplanation:
        "Linea destinata a un’utenza specifica, come forno, climatizzazione o altri carichi dedicati, dimensionata in base alla potenza richiesta.",
      note: "Fascia editoriale Esigenta: non esiste una sezione fissa universale per \"circuito dedicato\", la sezione viene dimensionata in funzione del carico reale. I prezzari ufficiali quotano le sezioni tecniche corrispondenti come \"dorsale interna\" — 2×4 mmq + T a 218,75 €, 2×6 mmq + T a 253,05 € e 2×10 mmq + T a 361,86 € (Prezzario Emilia-Romagna 2025, unità abitativa tipo, sezioni maggiori tipicamente per linee dedicate a carichi specifici). Non è il montante contatore-quadro.",
      includes: "linea dal quadro dimensionata per il carico specifico, tubazione/percorso, conduttori di sezione adeguata, collegamenti",
      excludes: "grandi opere murarie, montante contatore-quadro",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-quadro-generale-4-circuiti",
      label: "Quadro generale — circa 4 circuiti protetti",
      category: "Quadro elettrico completo",
      categoryNote:
        "Le fasce fanno riferimento al numero orientativo di circuiti protetti, non ai moduli del centralino. Le tre configurazioni sono alternative e il dimensionamento reale dipende dall’impianto.",
      unit: "a corpo",
      range: "da 500 € a 800 €",
      plainExplanation:
        "Configurazione indicativa per circa 4 circuiti protetti, comprensiva di quadro, dispositivi di protezione, cablaggio interno, posa e verifica finale.",
      note: "Fascia editoriale Esigenta: nessun prezzario consultato quota un quadro completo come pacchetto unico, solo singoli componenti. Valori puntuali preservati come riferimento tecnico (Prezzario Emilia-Romagna 2025, salvo indicazione diversa): magnetotermico differenziale 173,32 €, centralino da incasso vuoto 6 moduli 66,61 €, centralino da incasso vuoto 12 moduli 85,57 €; blocco differenziale, configurazione base 151,66 €, intermedia 184,87 €, maggiorata 281,37 € (Prezzario Friuli Venezia Giulia 2025). Non rappresentano il costo di un quadro completo, cablato e configurato: sono i componenti tecnici con cui viene costruita la fascia editoriale qui sopra, non un totale alternativo da usare al loro posto.",
      includes: "involucro/centralino adeguato, dispositivi di protezione coerenti con la configurazione, protezione dei circuiti, cablaggi interni, morsetti e accessori, identificazione dei circuiti, montaggio, collegamenti, verifica finale",
      excludes: "protezioni o configurazioni particolari non ordinarie (dipendono dal progetto/caso reale), quadro condominiale o di parti comuni",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-quadro-generale-6-circuiti",
      label: "Quadro generale — circa 6 circuiti protetti",
      category: "Quadro elettrico completo",
      unit: "a corpo",
      range: "da 650 € a 1.000 €",
      plainExplanation:
        "Configurazione indicativa per circa 6 circuiti protetti, comprensiva di quadro, dispositivi di protezione, cablaggio interno, posa e verifica finale.",
      note: "Stesso principio della fascia da 4 circuiti qui sopra: nessun prezzario consultato quota un quadro completo come pacchetto unico. Il numero di moduli del centralino necessario dipende dalla configurazione reale (interruttore generale, differenziali, magnetotermici) e può essere superiore a 6.",
      includes: "involucro/centralino adeguato, dispositivi di protezione coerenti con la configurazione, protezione dei circuiti, cablaggi interni, morsetti e accessori, identificazione dei circuiti, montaggio, collegamenti, verifica finale",
      excludes: "protezioni o configurazioni particolari non ordinarie (dipendono dal progetto/caso reale), quadro condominiale o di parti comuni",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-quadro-generale-8-10-circuiti",
      label: "Quadro generale — circa 8–10 circuiti protetti",
      category: "Quadro elettrico completo",
      unit: "a corpo",
      range: "da 850 € a 1.400 €",
      plainExplanation:
        "Configurazione indicativa per circa 8–10 circuiti protetti, comprensiva di quadro, dispositivi di protezione, cablaggio interno, posa e verifica finale.",
      note: "Stesso principio delle fasce qui sopra: nessun prezzario consultato quota un quadro completo come pacchetto unico. Non presuppone un'architettura fissa di differenziali/magnetotermici valida per ogni abitazione: la configurazione reale dipende dal progetto.",
      includes: "involucro/centralino adeguato, dispositivi di protezione coerenti con la configurazione, protezione dei circuiti, cablaggi interni, morsetti e accessori, identificazione dei circuiti, montaggio, collegamenti, verifica finale",
      excludes: "protezioni o configurazioni particolari non ordinarie (dipendono dal progetto/caso reale), quadro condominiale o di parti comuni",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "elettrico-traccia-muratura-mattoni-forati",
      label: "Traccia e chiusura grezza — laterizio/forato",
      simpleLabel: "Apertura e chiusura grezza del muro per i cavi — mattoni forati",
      category: "Opere murarie",
      categoryNote:
        "Le fasce riguardano l’apertura della traccia e la successiva chiusura grezza.",
      unit: "al metro",
      unitLabel: "per metro di traccia",
      range: "da 15 € a 25 € al metro",
      plainExplanation:
        "Apertura e chiusura grezza della traccia su muratura in laterizio o mattoni forati.",
      note: "Fascia editoriale Esigenta (era prezzo ufficiale puntuale: 15,92 € al metro, Prezzario Emilia-Romagna 2025, capitolato generale edilizia non specifico dell'impiantistica elettrica, fino a 100 cmq di sezione).",
      includes: "apertura, normale assistenza/posa, fissaggio, chiusura grezza",
      excludes: "intonaco finale diffuso, rasatura, tinteggiatura, finitura estetica uniforme, trasporto e smaltimento delle macerie quando non già compresi",
      confidence: "media",
      costType: "work",
    },
    {
      id: "elettrico-traccia-muratura-mattoni-pieni",
      label: "Traccia e chiusura grezza — muratura piena/difficile",
      simpleLabel: "Apertura e chiusura grezza del muro per i cavi — mattoni pieni",
      category: "Opere murarie",
      unit: "al metro",
      unitLabel: "per metro di traccia",
      range: "da 20 € a 35 € al metro",
      plainExplanation:
        "Apertura e chiusura grezza della traccia su muratura piena o più impegnativa da lavorare.",
      note: "Fascia editoriale Esigenta (era prezzo ufficiale puntuale: 20,61 € al metro, Prezzario Emilia-Romagna 2025, capitolato generale edilizia non specifico dell'impiantistica elettrica, fino a 100 cmq di sezione).",
      includes: "apertura, normale assistenza/posa, fissaggio, chiusura grezza",
      excludes: "intonaco finale diffuso, rasatura, tinteggiatura, finitura estetica uniforme, trasporto e smaltimento delle macerie quando non già compresi",
      confidence: "media",
      costType: "work",
    },
    {
      id: "elettrico-collegamento-equipotenziale",
      label: "Collegamento equipotenziale locale o di un vano",
      simpleLabel: "Collegamenti di sicurezza del locale (es. bagno)",
      technicalCode: "D01.001.025",
      category: "Collegamenti di sicurezza",
      unit: "cadauno",
      unitLabel: "per collegamento",
      range: "188,81 € cad",
      plainExplanation:
        "Collega tra loro le parti conduttrici previste in un locale (tipicamente il bagno). Non è una presa, un punto luce o il rifacimento completo della messa a terra dell'abitazione.",
      note: "Prezzario Regione Emilia-Romagna 2025, metodo sintetico (D01.001), per vano con masse metalliche da collegare. Se serve un intervento più generale sull'impianto di terra (dispersore, conduttore di protezione principale), vedi \"Adeguamento / rifacimento impianto di terra\" più sotto: sono due lavorazioni diverse.",
      includes: "conduttore di protezione, collegamenti e morsettiera equipotenziale del vano",
      excludes: "opere murarie, collegamento a dispersore di terra esterno al vano",
      costType: "complete",
    },
    {
      id: "elettrico-ripristino-estetico-tracce",
      label: "Ripristino estetico finale dopo le tracce",
      category: "Costi da valutare con il professionista",
      range: "da valutare con il professionista",
      plainExplanation:
        "Riguarda riprese di intonaco, rasatura e tinteggiatura necessarie a uniformare pareti o locali dopo l'apertura di nuove tracce: la chiusura grezza compresa nelle lavorazioni murarie qui sopra non è una parete pronta da pitturare.",
      note: "Non è quotabile con un prezzo al metro: la necessità può riguardare una porzione limitata di parete oppure un'intera parete o stanza, a seconda di quanto le tracce sono estese e visibili una volta chiuse.",
      priceStatus: "quoteRequired",
      role: "extra",
    },
    {
      id: "elettrico-montante-contatore-quadro",
      label: "Montante contatore → quadro appartamento",
      category: "Costi da valutare con il professionista",
      range: "da valutare con il professionista",
      plainExplanation:
        "È il tratto tra il contatore e il quadro generale dell'appartamento, a monte di tutte le altre voci di questa guida: i circuiti interni partono dal quadro, non dal contatore.",
      note: "Il costo dipende da distanza, sezione, piano, percorso, parti comuni e condizioni del cavidotto esistente: nessun prezzario consultato permette di attribuire un codice o un prezzo puntuale affidabile senza queste informazioni.",
      priceStatus: "quoteRequired",
      role: "extra",
    },
    {
      id: "elettrico-adeguamento-impianto-terra",
      label: "Adeguamento / rifacimento impianto di terra",
      category: "Costi da valutare con il professionista",
      range: "da valutare con il professionista",
      plainExplanation:
        "Riguarda un intervento generale sull'impianto di terra dell'edificio (dispersore, conduttore di protezione principale, collegamenti), non il singolo collegamento equipotenziale di un locale.",
      note: "Il costo dipende dall'impianto di terra esistente, dal tipo di edificio (singolo o condominiale), dal dispersore, dai conduttori principali e dalle verifiche necessarie. Non va confuso con \"Collegamento equipotenziale locale o di un vano\" qui sopra, che riguarda solo i collegamenti di un singolo locale.",
      priceStatus: "quoteRequired",
      role: "extra",
    },
  ],
  sizeExamples: [
    {
      label: "Impianto per 50 mq",
      sizeRange: "50 mq",
      range: "da 2.750 € a 4.500 €",
      note: "Calcolo per il rifacimento completo standard: 50 mq × 55–90 €/mq. Su un appartamento piccolo il costo al mq può risultare più alto: quadro, nuova uscita, verifiche e lavorazioni minime non diminuiscono in proporzione alla superficie.",
    },
    {
      label: "Impianto per 80 mq",
      sizeRange: "80 mq",
      range: "da 4.400 € a 7.200 €",
      note: "Calcolo per il rifacimento completo standard: 80 mq × 55–90 €/mq.",
    },
    {
      label: "Impianto per 100 mq",
      sizeRange: "100 mq",
      range: "da 5.500 € a 9.000 €",
      note: "Calcolo per il rifacimento completo standard: 100 mq × 55–90 €/mq.",
    },
    {
      label: "Impianto per 150 mq",
      sizeRange: "150 mq",
      range: "da 8.250 € a 13.500 €",
      note: "Calcolo per il rifacimento completo standard: 150 mq × 55–90 €/mq.",
    },
  ],
};
