import type { BasePriceRange } from "../../shared/types";

export const rifareFacciataPricing: BasePriceRange = {
  nationalRange: "70–120 € al mq",
  pricePerSquareMeter: "da 70 € a 120 € al mq",
  sourceLabel: "Prezzari regionali ufficiali e confronto di mercato nazionale",
  sourceYear: "2025–2026",
  sourceType: "mixed",
  priceRows: [
    {
      id: "facciata-rinnovo-finitura",
      label: "Rinnovo della finitura",
      category: "Scenari di ampiezza del lavoro",
      categoryNote:
        "Questi tre scenari rappresentano modi diversi di rifare una facciata, in ordine di ampiezza del degrado da trattare: scegli quello più vicino al tuo caso, non sommare le fasce tra loro. Il ponteggio, quando serve, resta sempre una voce a parte (vedi più sotto in tabella).",
      unit: "al mq",
      range: "da 25 € a 40 € al mq",
      plainExplanation:
        "È lo scenario più leggero: la facciata è sostanzialmente sana, senza intonaco diffuso da rifare. Si pulisce e prepara la superficie, si applica un fissativo solo se il fondo lo richiede, e si rifà la pittura o la finitura, con piccoli ripristini puntuali dove serve.",
      note: "Si applica quando l'intonaco esistente è compatto, senza crepe diffuse o distacchi importanti: il lavoro resta concentrato su pulizia, eventuale preparazione del fondo e nuova finitura. Non è una semplice tinteggiatura spacciata per rifacimento: se emergono zone di intonaco che si sta staccando, il lavoro rientra negli altri due scenari di questa guida.",
      includes:
        "pulizia e preparazione della superficie, fissativo quando il fondo lo richiede, nuova pittura o finitura, piccoli ripristini limitati",
      excludes: "demolizione diffusa dell'intonaco, nuovo intonaco esteso, rasatura armata estesa, ponteggio",
      confidence: "media",
      costType: "complete",
      role: "scenario",
    },
    {
      id: "facciata-ripristino-parziale",
      label: "Ripristino parziale e nuova finitura",
      category: "Scenari di ampiezza del lavoro",
      unit: "al mq",
      range: "da 45 € a 80 € al mq",
      plainExplanation:
        "È l'intervento adatto a un degrado localizzato: alcune zone della facciata hanno intonaco che si sta staccando, mentre il resto della superficie è ancora in condizioni accettabili. Si rimuovono solo le parti ammalorate, si ripristina l'intonaco dove serve, si regolarizza con la rasatura e si applica la nuova finitura.",
      note: "Perimetro intermedio tra il rinnovo della finitura e il rifacimento esteso qui sotto: la quantità di intonaco da rimuovere e rifare resta circoscritta a zone specifiche, non a tutta la facciata. Il ponteggio, quando serve per raggiungere quelle zone, resta una voce a parte.",
      includes:
        "rimozione delle zone di intonaco ammalorato, ripristino dell'intonaco dove necessario, rasatura delle zone interessate, preparazione, nuova finitura",
      excludes: "ponteggio",
      confidence: "media",
      costType: "complete",
      role: "scenario",
    },
    {
      id: "facciata-rifacimento-ordinario",
      label: "Rifacimento esteso della facciata",
      category: "Scenari di ampiezza del lavoro",
      unit: "al mq",
      range: "da 70 € a 120 € al mq",
      plainExplanation:
        "È lo scenario principale di questa guida: la facciata ha un degrado più diffuso, non limitato a poche zone. Si controllano le parti distaccate, si rimuove una quantità significativa di intonaco ammalorato, si ripristina, si regolarizza con la rasatura, si prepara il fondo e si applica la nuova finitura.",
      note: "È la fascia principale di questa guida, non una semplice tinteggiatura: comprende il ciclo completo quando il degrado dell'intonaco è diffuso, non solo localizzato. Una rasatura armata molto estesa, su superfici molto ampie da regolarizzare, può portare il lavoro oltre questa fascia — non per questo diventa uno scenario a sé: resta lo stesso tipo di intervento, solo più esteso. Il ponteggio e il cappotto termico restano sempre esclusi, qualunque sia lo scenario scelto in questa guida.",
      includes:
        "controllo delle parti distaccate, rimozione significativa dell'intonaco ammalorato, ripristino dell'intonaco, rasatura, preparazione, nuova finitura",
      excludes: "ponteggio, cappotto termico",
      confidence: "media",
      costType: "complete",
      role: "primary",
    },
    {
      id: "facciata-battitura-controllo",
      label: "Battitura e controllo delle parti distaccate",
      category: "Controllo e pulizia della facciata",
      unit: "al mq",
      range: "da 2 € a 4 € al mq",
      plainExplanation:
        "Controllo manuale della facciata per individuare zone di intonaco vuote, distaccate o non più aderenti, chiamato anche battitura o picchettatura di verifica.",
      note: "Spesso è già compresa nel lavoro generale di ripristino, quando la stessa impresa esegue anche la rimozione e il rifacimento dell'intonaco: in quel caso può non comparire come voce a parte nel preventivo. Ponteggio escluso.",
      confidence: "media",
      costType: "work",
    },
    {
      id: "facciata-lavaggio-pulizia",
      label: "Lavaggio e pulizia della facciata",
      category: "Controllo e pulizia della facciata",
      unit: "al mq",
      range: "da 4 € a 8 € al mq",
      plainExplanation:
        "Pulizia della superficie da sporco e depositi prima delle lavorazioni successive, con idrolavaggio quando compatibile con il supporto.",
      note: "L'idrolavaggio non è sempre lo strumento più adatto: su supporti fragili o già ammalorati l'impresa può preferire un metodo di pulizia meno aggressivo. Non comprende il trattamento di muffe o degrado che richiede cicli specifici, né il ponteggio.",
      includes: "pulizia/idrolavaggio quando compatibile con il supporto, rimozione ordinaria di sporco e depositi superficiali",
      excludes: "ripristini, trattamento di muffe o degrado specialistico quando richiede cicli specifici, ponteggio",
      confidence: "media",
      costType: "work",
    },
    {
      id: "facciata-rimozione-intonaco-ammalorato",
      label: "Rimozione dell'intonaco ammalorato",
      category: "Demolizione e ripristino dell'intonaco",
      unit: "al mq",
      range: "da 14 € a 20 € al mq",
      plainExplanation:
        "Rimozione delle parti di intonaco deteriorate o distaccate, detta anche spicconatura, con pulizia del supporto sottostante.",
      note: "Comprende la normale gestione, il trasporto e lo smaltimento del materiale rimosso. Il costo si applica alla quantità reale di intonaco da rimuovere, non all'intera superficie della facciata: riguarda solo le zone ammalorate individuate nel controllo iniziale.",
      includes:
        "spicconatura/rimozione delle parti deteriorate, pulizia del supporto, gestione, trasporto e smaltimento ordinari del materiale rimosso",
      excludes: "ponteggio",
      confidence: "media",
      costType: "work",
    },
    {
      id: "facciata-ripristino-intonaco",
      label: "Ripristino / nuovo intonaco esterno",
      category: "Demolizione e ripristino dell'intonaco",
      unit: "al mq",
      range: "da 25 € a 40 € al mq",
      plainExplanation: "Realizzazione del nuovo intonaco nelle zone precedentemente rimosse, comprensiva di materiale e posa.",
      note: "Presuppone che la rimozione dell'intonaco ammalorato sia già stata eseguita: non la comprende (vedi la riga qui sopra). Non comprende la rasatura finale dell'intera facciata né la pittura: sono lavorazioni successive, con un prezzo proprio più sotto in tabella.",
      includes:
        "materiale, applicazione del nuovo intonaco nelle zone demolite, normale preparazione/aggrappo compatibile con il ciclo quando necessario",
      excludes: "ponteggio, demolizione precedente, rasatura finale dell'intera facciata, pittura",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "facciata-rasatura-semplice",
      label: "Rasatura semplice in due mani",
      category: "Rasature",
      categoryNote:
        "Rasatura semplice e rasatura armata sono alternative da scegliere in base alle condizioni del fondo, non lavorazioni da sommare sulla stessa superficie.",
      unit: "al mq",
      range: "da 15 € a 25 € al mq",
      plainExplanation:
        "Regolarizzazione della superficie con rasante applicato in due mani su un fondo già idoneo, prima della finitura.",
      note: "Presuppone un fondo già idoneo, non un intonaco appena rifatto su grandi superfici né molto irregolare: quando il fondo è più critico o la zona da regolarizzare è ampia, la scelta più adatta è di solito la rasatura armata qui sotto, non due rasature sommate sulla stessa parete.",
      includes: "rasante professionale, applicazione in due mani/passate, normale finitura del supporto",
      excludes:
        "grandi ripristini, demolizione intonaco, rete armata, pittura, ponteggio, primer specialistici quando contabilizzati separatamente",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "facciata-rasatura-armata",
      label: "Rasatura armata con rete",
      category: "Rasature",
      unit: "al mq",
      range: "da 25 € a 40 € al mq",
      plainExplanation:
        "Rasatura con rete in fibra di vetro annegata nel rasante, indicata per fondi più critici o dopo ripristini estesi.",
      note: "Comprende l'annegamento della rete, le sovrapposizioni tra i teli e una seconda passata di rasatura di copertura. Non va sommata alla rasatura semplice qui sopra: sono due configurazioni diverse dello stesso passaggio, si sceglie quella più adatta al proprio caso, non entrambe sulla stessa superficie.",
      includes: "rasante, rete in fibra di vetro, annegamento e sovrapposizioni, seconda passata/rasatura di copertura",
      excludes: "finitura pittorica, demolizione, ponteggio",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "facciata-fissativo-primer",
      label: "Fissativo, consolidante o primer",
      category: "Preparazione del fondo",
      unit: "al mq",
      range: "da 3 € a 7 € al mq",
      plainExplanation:
        "Può essere necessario su fondi assorbenti, sfarinanti o con scarsa adesione prima della finitura. Il prodotto e il ciclo da utilizzare dipendono dalle condizioni del supporto.",
      note: "Da conteggiare separatamente solo quando non è già compreso nel ciclo successivo: alcuni cicli di pittura (in particolare alcune pitture silossaniche) comprendono già un fissativo compatibile nel proprio sistema. Non va sommato automaticamente alla tinteggiatura: verifica con l'impresa se il ciclo scelto lo comprende già.",
      confidence: "media",
      costType: "complete",
      role: "extra",
      relations: [
        { type: "addsTo", target: "facciata-tinteggiatura-acrilica" },
        { type: "addsTo", target: "facciata-pittura-silossanica" },
        { type: "addsTo", target: "facciata-rivestimento-a-spessore" },
      ],
    },
    {
      id: "facciata-tinteggiatura-acrilica",
      label: "Tinteggiatura esterna acrilica o al quarzo",
      category: "Finiture",
      unit: "al mq",
      range: "da 16 € a 25 € al mq",
      plainExplanation:
        "Finitura pittorica esterna, normalmente in due mani, applicata su una facciata già preparata.",
      note: "Il fissativo, quando serve, non è compreso in questo prezzo (vedi \"Fissativo, consolidante o primer\" qui sopra) — non va comunque duplicato se il ciclo di pittura scelto lo comprende già.",
      includes: "preparazione ordinaria, due mani di pittura",
      excludes: "ponteggio, fissativo quando non già compreso nel ciclo",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "facciata-pittura-silossanica",
      label: "Pittura silossanica",
      category: "Finiture",
      unit: "al mq",
      range: "da 22 € a 35 € al mq",
      plainExplanation:
        "Finitura esterna traspirante e idrorepellente, applicata su un fondo preparato con ciclo compatibile.",
      note: "Va chiaramente distinta dal rivestimento a spessore qui sotto: è una pittura a film sottile, non una finitura granulata o frattazzata. Il prezzo più alto rispetto alla tinteggiatura standard riflette la tecnologia del prodotto (traspirabilità, idrorepellenza), non solo l'aspetto estetico.",
      includes: "fondo idoneo, fissativo compatibile quando previsto dal ciclo, due mani",
      excludes: "ponteggio",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "facciata-rivestimento-a-spessore",
      label: "Rivestimento a spessore / intonachino",
      category: "Finiture",
      unit: "al mq",
      range: "da 25 € a 40 € al mq",
      plainExplanation:
        "Finitura granulata o frattazzata applicata a spessore, che modifica texture e protezione superficiale oltre al colore.",
      note: "Può essere a base silossanica o un'altra tecnologia compatibile con il sistema scelto: questa riga non si restringe a una sola tecnologia di rivestimento a spessore.",
      excludes: "ponteggio",
      confidence: "media",
      costType: "complete",
    },
    {
      id: "facciata-ponteggio",
      label: "Ponteggio",
      category: "Ponteggio",
      unit: "al mq di facciata",
      range: "da 15 € a 30 € al mq di facciata",
      plainExplanation:
        "Ponteggio necessario per lavorare in sicurezza, calcolato sulla superficie della facciata da ponteggiare.",
      note: "Comprende orientativamente montaggio, un periodo iniziale di utilizzo/noleggio e smontaggio. Periodi di noleggio più lunghi possono far salire il costo. Resta sempre una voce separata dai range principali di questa guida, qualunque sia lo scenario o le lavorazioni scelte.",
      includes: "montaggio, periodo iniziale di utilizzo/noleggio, smontaggio",
      excludes:
        "occupazione di suolo pubblico, configurazioni particolari, protezioni speciali, noleggio molto prolungato, autorizzazioni e oneri specifici",
      confidence: "media",
      costType: "work",
    },
  ],
  sizeExamples: [
    {
      label: "Facciata da 100 mq",
      sizeRange: "100 mq",
      range: "da 7.000 € a 12.000 €",
      note: "Calcolo per il rifacimento esteso: 100 mq × 70–120 €/mq. Ponteggio escluso.",
    },
    {
      label: "Facciata da 200 mq",
      sizeRange: "200 mq",
      range: "da 14.000 € a 24.000 €",
      note: "Calcolo per il rifacimento esteso: 200 mq × 70–120 €/mq. Ponteggio escluso.",
    },
    {
      label: "Facciata da 300 mq",
      sizeRange: "300 mq",
      range: "da 21.000 € a 36.000 €",
      note: "Calcolo per il rifacimento esteso: 300 mq × 70–120 €/mq. Ponteggio escluso.",
    },
  ],
};
