import type { CostGuidePricePresentation } from "./types";

export const costGuidePricePresentationBySlug: Readonly<Record<string, CostGuidePricePresentation>> = {
  "ristrutturare-bagno": {
    scenarios: [
      { rowId: "bagno-rinnovo-leggero",
        label: "Può comprendere",
        items: [
          "mantenimento degli impianti esistenti se in buono stato",
          "sostituzione dei sanitari",
          "rinnovo di pavimenti o rivestimenti senza demolizione completa, dove possibile",
          "sostituzione di rubinetteria e finiture",
          "interventi locali di ripristino",
        ],
      },
      { rowId: "bagno-ristrutturazione-completa",
        label: "Comprende",
        items: [
          "rimozione dei sanitari esistenti",
          "demolizione ordinaria di pavimento e rivestimenti",
          "trasporto e smaltimento ordinari",
          "rifacimento dell’impianto idraulico interno",
          "impermeabilizzazione nelle zone necessarie",
          "posa di pavimenti e rivestimenti standard",
          "sanitari standard e normali finiture",
        ],
      },
      { rowId: "bagno-ristrutturazione-complessa",
        label: "Può comprendere",
        items: [
          "superficie maggiore",
          "più punti acqua o sanitari",
          "spostamento degli scarichi",
          "doccia a filo pavimento",
          "opere murarie più articolate",
          "materiali o finiture di fascia superiore",
        ],
      },
    ],
  },
  "ristrutturare-cucina": {
    scenarios: [
      { rowId: "cucina-rinnovo-impianti-invariati", label: "Può comprendere", items: ["rivestimenti e ripristini locali", "piccoli adattamenti", "impianti principali mantenuti"] },
      { rowId: "cucina-ristrutturazione-adeguamento-impianti", label: "Comprende", items: ["rinnovo di rivestimenti e pareti", "adeguamenti elettrici e idraulici ordinari", "ripristini e finiture", "pavimento, massetto e arredo non inclusi automaticamente"] },
      { rowId: "cucina-ristrutturazione-modifica-disposizione", label: "Può comprendere", items: ["spostamenti più estesi di acqua e scarico", "nuove distribuzioni elettriche", "opere murarie", "eventuali lavori a terra quando necessari"] },
    ],
    extras: [
      { rowId: "cucina-rifacimento-pavimento" },
      { rowId: "cucina-demolizione-massetto" },
      { rowId: "cucina-rifacimento-massetto" },
      { rowId: "cucina-scarico-importante" },
      { rowId: "cucina-tramezzo" },
      { rowId: "cucina-gas" },
      { rowId: "cucina-controsoffitto" },
      { rowId: "cucina-isola-penisola" },
    ],
    breakdown: [
      { rowId: "cucina-rimozione-rivestimenti", show: true }, { rowId: "cucina-smaltimento-materiali", show: true },
      { rowId: "cucina-punto-presa", show: true }, { rowId: "cucina-adeguamento-elettrico", show: true }, { rowId: "cucina-linea-induzione", show: true },
      { rowId: "cucina-punto-acqua", show: true }, { rowId: "cucina-adeguamento-acqua-scarico", show: true },
      { rowId: "cucina-chiusura-tracce", show: true }, { rowId: "cucina-ripristino-intonaco", show: true }, { rowId: "cucina-rasatura-parete", show: true },
      { rowId: "cucina-posa-rivestimento", show: true }, { rowId: "cucina-tinteggiatura", show: true },
      { rowId: "cucina-rifacimento-pavimento", show: true }, { rowId: "cucina-demolizione-massetto", show: true }, { rowId: "cucina-rifacimento-massetto", show: true },
      { rowId: "cucina-scarico-importante", show: true }, { rowId: "cucina-tramezzo", show: true }, { rowId: "cucina-gas", show: true }, { rowId: "cucina-controsoffitto", show: true }, { rowId: "cucina-isola-penisola", show: true }, { rowId: "cucina-arredo", show: true },
    ],
  },
  "rifare-tetto": {
    scenarios: [
      { rowId: "tetto-sostituzione-manto", title: "Sostituzione del solo manto", label: "Può comprendere", items: ["rimozione del vecchio manto", "posa di tegole, coppi o altra copertura standard", "lavorazioni ordinarie sul supporto esistente"] },
      { rowId: "tetto-rifacimento-copertura", title: "Rifacimento standard della copertura", label: "Comprende", items: ["rimozione e smaltimento del vecchio manto", "preparazione ordinaria del supporto", "impermeabilizzazione", "nuovo manto e posa"] },
      { rowId: "tetto-rifacimento-isolamento-ventilazione", title: "Rifacimento con isolamento o ventilazione", label: "Può comprendere", items: ["lavorazioni del rifacimento standard", "isolamento termico", "stratigrafia più evoluta", "tetto ventilato"] },
      { rowId: "tetto-rifacimento-struttura", title: "Rifacimento con interventi strutturali", label: "Può comprendere", items: ["rifacimento della copertura", "interventi su travi", "interventi sull’orditura", "interventi sul solaio, quando necessari"] },
    ],
  },
  "rifare-facciata": {
    scenarios: [
      { rowId: "facciata-rinnovo-finitura", title: "Rinnovo della finitura", label: "Quando può bastare", items: ["La facciata è sostanzialmente sana e non presenta un degrado diffuso dell’intonaco."] },
      { rowId: "facciata-ripristino-parziale", title: "Ripristino parziale e nuova finitura", label: "Quando può bastare", items: ["Il degrado è localizzato: alcune zone richiedono il ripristino dell’intonaco, mentre il resto della facciata è ancora in condizioni accettabili."] },
      { rowId: "facciata-rifacimento-ordinario", title: "Rifacimento esteso della facciata", label: "Comprende", items: ["controllo delle parti distaccate", "rimozione significativa dell’intonaco ammalorato", "ripristino dell’intonaco", "rasatura", "preparazione del fondo", "nuova finitura"] },
    ],
  },
  "rifare-impianto-elettrico": {
    scenarios: [
      { rowId: "elettrico-scenario-canalizzazioni-riutilizzabili", title: "Canalizzazioni esistenti riutilizzabili", label: "Può comprendere", items: ["Riutilizzo delle canalizzazioni esistenti", "Adeguamento o sostituzione delle linee", "Punti luce, prese e comandi necessari", "Adeguamento di quadro e protezioni, dove previsto"] },
      { rowId: "elettrico-rifacimento-completo", title: "Rifacimento completo standard", label: "Comprende", items: ["Nuovo impianto elettrico interno", "Distribuzione dei circuiti ordinari", "Punti luce, prese e comandi standard", "Quadro generale e protezioni", "Normali tracce necessarie", "Chiusura grezza delle tracce"] },
      { rowId: "elettrico-scenario-impianto-articolato", title: "Impianto più articolato", label: "Può comprendere", items: ["Maggiore suddivisione dei circuiti", "Più linee dedicate", "Quadro elettrico più articolato", "Nuove tracce più diffuse", "Maggior numero di punti", "Distribuzione più complessa"] },
    ],
    extras: [
      { rowId: "elettrico-ripristino-estetico-tracce", title: "Ripristino estetico finale", description: "Rasatura, tinteggiatura e finiture necessarie dopo la chiusura grezza delle tracce." },
      { rowId: "elettrico-montante-contatore-quadro", title: "Montante contatore → quadro", description: "Intervento sul collegamento tra contatore e quadro generale dell’abitazione." },
      { rowId: "elettrico-adeguamento-impianto-terra", title: "Adeguamento o rifacimento della messa a terra", description: "Intervento generale sull’impianto di terra quando quello esistente richiede adeguamenti." },
    ],
  },
  "impermeabilizzare-tetto": {
    scenarios: [
      { rowId: "impermeabilizzare-tetto-scenario-guaina-standard",
        label: "Comprende",
        items: [
          "membrana bituminosa liscia",
          "materiale",
          "posa",
          "normale impermeabilizzazione della superficie",
          "finitura non autoprotetta",
        ],
      },
      { rowId: "impermeabilizzare-tetto-scenario-guaina-ardesiata",
        label: "Comprende",
        items: [
          "membrana bituminosa ardesiata",
          "materiale",
          "posa",
          "protezione superficiale minerale",
          "soluzione adatta quando la guaina resta esposta",
        ],
      },
      { rowId: "impermeabilizzare-tetto-scenario-doppio-strato",
        label: "Può comprendere",
        items: [
          "due membrane bituminose sovrapposte",
          "maggiore protezione della copertura",
          "finitura standard oppure autoprotetta",
          "protezione in alluminio nei sistemi più evoluti",
          "protezione in rame nelle soluzioni di fascia più alta",
          "Fascia: 35–55 €/m² doppio strato standard, 45–60 €/m² con alluminio, 75–90 €/m² con rame.",
        ],
      },
    ],
    breakdown: [
      { rowId: "impermeabilizzare-tetto-scenario-guaina-standard", show: true },
      { rowId: "impermeabilizzare-tetto-scenario-guaina-ardesiata", show: true },
      { rowId: "impermeabilizzare-tetto-scenario-doppio-strato", show: true },
      { rowId: "impermeabilizzare-tetto-lisciatura-piano-posa", show: true },
      { rowId: "impermeabilizzare-tetto-rimozione-smaltimento-guaina", show: true },
    ],
  },
  "impermeabilizzare-terrazzo": {
    scenarios: [
      { rowId: "impermeabilizzare-terrazzo-cementizia-sotto-pavimento", label: "Comprende", items: ["sistema impermeabilizzante cementizio", "materiale", "applicazione", "posa su supporto idoneo", "preparazione ordinaria prevista dal ciclo", "La nuova pavimentazione finale non è compresa."] },
      { rowId: "impermeabilizzare-terrazzo-trasparente-sopra-piastrelle", label: "Può comprendere", items: ["sistema trasparente compatibile", "materiale", "applicazione", "mantenimento della pavimentazione esistente", "intervento senza demolizione quando il supporto è stabile e idoneo"] },
      { rowId: "impermeabilizzare-terrazzo-resina-calpestabile-vista", label: "Comprende", items: ["ciclo resinoso impermeabilizzante", "materiale", "applicazione", "finitura finale continua", "superficie progettata per normale traffico pedonale", "eventuale finitura antiscivolo quando prevista dal sistema"] },
    ],
    extras: [
      { rowId: "impermeabilizzare-terrazzo-demolizione-pavimento-esistente", description: "Si aggiunge quando la pavimentazione esistente deve essere rimossa prima dell’impermeabilizzazione; non è necessaria nei sistemi applicabili sopra un pavimento stabile e idoneo." },
      { rowId: "impermeabilizzare-terrazzo-ripristino-massetto-pendenze", description: "Può essere necessario quando il massetto è deteriorato o le pendenze non consentono un corretto deflusso dell’acqua." },
    ],
    breakdown: [
      { rowId: "impermeabilizzare-terrazzo-cementizia-sotto-pavimento", show: true },
      { rowId: "impermeabilizzare-terrazzo-trasparente-sopra-piastrelle", show: true },
      { rowId: "impermeabilizzare-terrazzo-resina-calpestabile-vista", show: true },
      { rowId: "impermeabilizzare-terrazzo-demolizione-pavimento-esistente", show: true },
      { rowId: "impermeabilizzare-terrazzo-ripristino-massetto-pendenze", show: true },
    ],
  },
  "rifare-pavimenti": {
    scenarios: [
      { rowId: "pavimenti-scenario-sovrapposizione",
        label: "Comprende",
        items: [
          "mantenimento del pavimento esistente quando stabile e idoneo",
          "preparazione ordinaria del fondo",
          "gres standard/medio",
          "collante",
          "posa",
          "stuccatura",
        ],
      },
      { rowId: "pavimenti-rifacimento-standard",
        label: "Comprende",
        items: [
          "rimozione del vecchio pavimento",
          "gestione ordinaria dello smaltimento",
          "mantenimento del massetto esistente quando recuperabile",
          "normale preparazione del fondo",
          "gres standard/medio",
          "collante, posa e stuccatura",
        ],
      },
      { rowId: "pavimenti-rifacimento-nuovo-massetto",
        label: "Può comprendere",
        items: [
          "demolizione del pavimento esistente",
          "rimozione del sottofondo quando necessaria",
          "smaltimento ordinario",
          "nuovo massetto",
          "gres standard/medio",
          "posa e stuccatura",
        ],
      },
    ],
  },
};
